In [1]:
import numpy as np

X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],  # стаж
              [500, 700, 750, 600, 1450,        # средняя стоимость занятия
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], dtype = np.float64) # квалификация репетитора

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

X_st = X.copy()
X_st[1:] = calc_std_feat(X[1, :])
X_st

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [-0.57142857, -0.57142857, -0.21428571, -0.57142857,  0.14285714,
        -0.92857143,  0.85714286,  2.64285714, -0.57142857, -0.21428571],
       [-0.57142857, -0.57142857, -0.21428571, -0.57142857,  0.14285714,
        -0.92857143,  0.85714286,  2.64285714, -0.57142857, -0.21428571],
       [-0.57142857, -0.57142857, -0.21428571, -0.57142857,  0.14285714,
        -0.92857143,  0.85714286,  2.64285714, -0.57142857, -0.21428571]])

In [2]:
def calc_logloss(y, y_pred):
    err = np.mean(- y * np.log(y_pred) - (1.0 - y) * np.log(1.0 - y_pred))
    return err

def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

#### Подберите аргументы функции eval_LR_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [3]:
def eval_LR_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations + 1):
        z = np.dot(w, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

w = eval_LR_model(X_st, y, iterations=1000, alpha=1e-2)

100 [ 0.46008808 -0.35234117  0.43361167  1.30895299] 0.8840532931154783
200 [ 0.39559962 -0.52659349  0.25935935  1.13470066] 0.7880035088949489
300 [ 0.32167539 -0.65435887  0.13159397  1.00693529] 0.7326577682657607
400 [ 0.25396447 -0.73349665  0.05245618  0.9277975 ] 0.708597015438033
500 [ 0.1985006  -0.77575468  0.01019816  0.88553948] 0.699879089871958
600 [ 0.15473729 -0.79666194 -0.0107091   0.86463222] 0.6965642485311496
700 [ 0.12053441 -0.80670478 -0.02075194  0.85458938] 0.6950642075693991
800 [ 0.09386785 -0.81147621 -0.02552337  0.84981795] 0.694274487693436
900 [ 0.07309249 -0.81373317 -0.02778033  0.84756099] 0.6938228285388804
1000 [ 0.05691175 -0.81479863 -0.02884579  0.84649553] 0.6935550558571459


In [4]:
w = eval_LR_model(X_st, y, iterations=10000000, alpha=1e-3)

1000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
2000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
3000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
4000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
5000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
6000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
7000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
8000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
9000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
10000000 [-1.04947588e-16 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453


In [5]:
w = eval_LR_model(X_st, y, iterations=10000, alpha=1e-2)

1000 [ 0.05691175 -0.81479863 -0.02884579  0.84649553] 0.6935550558571459
2000 [ 0.00465763 -0.81574849 -0.02979565  0.84554567] 0.6931499058558985
3000 [ 3.81126950e-04 -8.15748999e-01 -2.97961594e-02  8.45545159e-01] 0.6931471988082919
4000 [ 3.11870302e-05 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471806821342
5000 [ 2.55198654e-06 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805607636
6000 [ 2.08825119e-07 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599507
7000 [ 1.70878372e-08 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599454
8000 [ 1.39827131e-09 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599452
9000 [ 1.14418352e-10 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599453
10000 [ 9.36264476e-12 -8.15748999e-01 -2.97961597e-02  8.45545159e-01] 0.6931471805599452


***Вывод:*** оптимальные значения $iter=10000, \alpha=0.01$

#### Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются веса, которые уже посчитаны функцией eval_LR_model и X, на выходе - массив y_pred_proba).

In [6]:
def calc_pred_proba(w, X):
    y_pred_proba = sigmoid(np.dot(w,X))
    return np.array(y_pred_proba, dtype = np.float64)

y_pred_proba = calc_pred_proba(w, X_st)
y_pred_proba

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

#### Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются веса, которые уже посчитаны функцией eval_LR_model и X, на выходе - массив y_pred).

In [7]:
def calc_pred(w, X):
    y_pred_proba = calc_pred_proba(w,X)
    y_pred = []
                      
    for y in y_pred_proba:
        if y > 0.5:
            y_pred.append(1)
        else:
            y_pred.append(0)
    
    return y_pred

y_pred = calc_pred(w, X_st)
y_pred

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

#### Посчитайте accuracy, матрицу ошибок, precision и recall, а также F1-score.

In [8]:
def accuracy(y, y_pred):
    return 1/len(y)*np.sum([1 for i,y_p in enumerate(y_pred) if y_p == y[i]])

accuracy(y, y_pred)

0.5

In [9]:
def err_matrix(y, y_pred):
    matrix = [[0,0],[0,0]]
    for i, y_p in enumerate(y_pred):
        if y_p == 1 and y_p == y[i]:
            matrix[0][0] += 1
        elif y_p == 0 and y_p == y[i]:
            matrix[0][1] += 1
        elif y_p == 1 and y_p != y[i]:
            matrix[1][0] += 1
        elif y_p == 0 and y_p != y[i]:
            matrix[1][1] += 1
    return matrix

m = err_matrix(y,y_pred)

print(f'TP: {m[0][0]}  TN: {m[0][1]}\nFP: {m[1][0]}  FN: {m[1][1]}')

TP: 5  TN: 0
FP: 5  FN: 0


In [10]:
def precision(y,y_pred):
    Err = err_matrix(y, y_pred)
    return Err[0][0]/(Err[0][0]+Err[1][0])

def recall(y, y_pred):
    Err = err_matrix(y, y_pred)
    return Err[0][0]/(Err[0][0]+Err[1][1])

p = precision(y,y_pred)
r = recall(y,y_pred)

print(f'Точность: {p}\nПолнота: {r}')

Точность: 0.5
Полнота: 1.0


In [11]:
def F1(p,r):
    return 2*p*r/(p+r)

F1(p,r)

0.6666666666666666

#### Могла ли модель переобучиться? Почему?

По полученным результатам сложно говорить о фактическом переобучении, тк точность довольно низкая для задач классификации, но, по-моему мнению, в силу своей простоты модель имеет склонность к переобучению на основании малого размера датасета, вследствии чего веса могут быть недостаточно точны для неизвестных данных.

#### *Создайте функции eval_LR_model_l1 и eval_LR_model_l2 с применением L1 и L2 регуляризации соответственно.

In [16]:
def eval_LR_model_l1(X, y, iterations, alpha=1e-4, lambda_ = 1e-8):
    np.random.seed(42)
    w = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations + 1):
        z = np.dot(w, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X.T) + lambda_ * w/np.abs(w))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

eval_LR_model_l1(X_st, y, iterations=10000, alpha=1e-2, lambda_=1e-5)

1000 [ 0.05687429 -0.81469184 -0.028847    0.84640232] 0.6935545307876223
2000 [ 0.00461783 -0.81557471 -0.02972987  0.84531945] 0.6931498596284236
3000 [ 3.41143725e-04 -8.15508554e-01 -2.96637150e-02  8.45185603e-01] 0.6931471952111335
4000 [ 5.72072512e-08 -8.15441888e-01 -2.95970486e-02  8.45052270e-01] 0.6931471805821677
5000 [ 5.06472161e-08 -8.15375221e-01 -2.95303819e-02  8.44918936e-01] 0.6931471805821678
6000 [ 5.01104185e-08 -8.15308555e-01 -2.94637152e-02  8.44785603e-01] 0.6931471805821678
7000 [ 5.00664932e-08 -8.15241888e-01 -2.93970486e-02  8.44652270e-01] 0.693147180582168
8000 [ 5.00628989e-08 -8.15175221e-01 -2.93303819e-02  8.44518936e-01] 0.6931471805821677
9000 [ 5.00626048e-08 -8.15108555e-01 -2.92637152e-02  8.44385603e-01] 0.6931471805821678
10000 [ 5.00625807e-08 -8.15041888e-01 -2.91970486e-02  8.44252270e-01] 0.6931471805821678


array([ 5.00625807e-08, -8.15041888e-01, -2.91970486e-02,  8.44252270e-01])

In [17]:
def eval_LR_model_l2(X, y, iterations, alpha=1e-4, lambda_ = 1e-8):
    np.random.seed(42)
    w = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations + 1):
        z = np.dot(w, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X.T) + 2 * lambda_ * w)
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

eval_LR_model_l2(X_st, y, iterations=10000, alpha=1e-2, lambda_=1e-5)

1000 [ 0.05689956 -0.81463574 -0.02884007  0.84632619] 0.6935548812735923
2000 [ 0.0046557  -0.81542225 -0.02978373  0.84520752] 0.69314990359727
3000 [ 3.80892531e-04 -8.15259696e-01 -2.97782871e-02  8.45037984e-01] 0.6931471987858582
4000 [ 3.11615995e-05 -8.15096661e-01 -2.97723323e-02  8.44868993e-01] 0.6931471806819353
5000 [ 2.54939438e-06 -8.14933658e-01 -2.97663784e-02  8.44700036e-01] 0.6931471805607619
6000 [ 2.08571184e-07 -8.14770687e-01 -2.97604257e-02  8.44531113e-01] 0.6931471805599507
7000 [ 1.70636364e-08 -8.14607749e-01 -2.97544742e-02  8.44362224e-01] 0.6931471805599454
8000 [ 1.39601104e-09 -8.14444844e-01 -2.97485239e-02  8.44193368e-01] 0.6931471805599454
9000 [ 1.14210474e-10 -8.14281971e-01 -2.97425748e-02  8.44024546e-01] 0.6931471805599454
10000 [ 9.34374284e-12 -8.14119131e-01 -2.97366269e-02  8.43855758e-01] 0.6931471805599454


array([ 9.34374284e-12, -8.14119131e-01, -2.97366269e-02,  8.43855758e-01])